# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: denpie.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'denpie.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61ilytip.proto\x12\x08\x64\x61ilytip\"U\n\tTipsQuery\x12\r\n\x05\x63ount\x18\x01 \x01(\x04\x12\x0e\n\x06topics\x18\x02 \x01(\t\x12\x13\n\x0btopic_class\x18\x03 \x01(\t\x12\x14\n\x0ctipcard_type\x18\x04 \x01(\t\"\x89\x01\n\x0fTipCardResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x14\n\x0c\x66ull_content\x18\x03 \x01(\t\x12\x1a\n\x12\x63ompressed_content\x18\x04 \x01(\t\x12\x13\n\x0btopic_class\x18\x05 \x01(\t\x12\x14\n\x0ctipcard_type\x18\x06 \x01(\t\"7\n\x0cTipsResponse\x12\'\n\x04tips\x18\x01 \x03(\x0b\x32\x19.denpie.TipCardResponse\"?\n\rReviewPayload\x12\x0f\n\x07\x63\x61rd_id\x18\x01 \x01(\x03\x12\r\n\x05grade\x18\x02 \x01(\r\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\"#\n\x11GetTopicsResponse\x12\x0e\n\x06topics\x18\x01 \x03(\t\"<\n\nTopicClass\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0ctipcard_type\x18\x03 \x01(\t\"@\n\x17GetTopicClassesResponse\x12%\n\x07\x63lasses\x18\x01 \x03(\x0b\x32\x14.denpie.TopicClassb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'denpie_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIPSQUERY']._serialized_start=28
  _globals['_TIPSQUERY']._serialized_end=113
  _globals['_TIPCARDRESPONSE']._serialized_start=116
  _globals['_TIPCARDRESPONSE']._serialized_end=253
  _globals['_TIPSRESPONSE']._serialized_start=255
  _globals['_TIPSRESPONSE']._serialized_end=310
  _globals['_REVIEWPAYLOAD']._serialized_start=312
  _globals['_REVIEWPAYLOAD']._serialized_end=375
  _globals['_GETTOPICSRESPONSE']._serialized_start=377
  _globals['_GETTOPICSRESPONSE']._serialized_end=412
  _globals['_TOPICCLASS']._serialized_start=414
  _globals['_TOPICCLASS']._serialized_end=474
  _globals['_GETTOPICCLASSESRESPONSE']._serialized_start=476
  _globals['_GETTOPICCLASSESRESPONSE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
